[[buildpacks]]
uri = "node-buildpack"

[[buildpacks]]
uri = "docker://rajavarman/package:300"

[[processes]]
  type = "web"
  command = "node index.js"

[[processes]]
  type = "web"
  default = true
  command = "node index.js"
